name: Build Samsung Driver Tool

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller customtkinter darkdetect packaging

    - name: Build Executable
      run: |
        # تم تعديل --add-data لتشمل الملفات من المسار الرئيسي مباشرة (.)
        # تم إضافة الملفين الخاصين بالنظامين (x64 و x86) لضمان عمل البرنامج عند المستخدم
        pyinstaller --onefile --noconsole --uac-admin `
        --collect-all customtkinter `
        --add-data "installer_x64.exe;." `
        --add-data "installer_x86.exe;." `
        --add-data "Gadget_Serial.inf;." `
        --add-data "Gadget_Serial.cat;." `
        --name "EKO_Samsung_Drivers_Pro" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Samsung-Pro-Installer
        path: dist/EKO_Samsung_Drivers_Pro.exe
